server:
  port: 5000
spring:
  application:
    name: api-geteway
zuul:
  routes:
    PROVIDER-SERVICE:
      path: /pro/**
      serviceId: PROVIDER
  prefix: /api   #http://localhost:5000/zuul/api/pro5551/getPort/wr?token=326666
#  ignored-services: PROVIDER5551-SERVICE
  ignored-patterns: /**/getPort/** # 路径中包含getPort被拒绝访问
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5555/eureka/